[package]
name = "rust-ferrite-nix-starter"
version = "0.1.0"
authors = ["M. Ian Graham <hello@miangraham.com>"]
edition = "2018"
license = "Unlicense OR MIT"

[dependencies]
ferrite-session = "0.1"
futures = "0.3"
log = "0.4"
pretty_env_logger = "0.4"
tokio = "1.6"
